[config]
skip_core_tasks = true

[tasks.devinstall]
command = "pip"
args = ["install", "-r", "requirements-dev.txt"]

[tasks.dev]
category = "development"
command = "python"
args = ["setup.py", "develop"]

[tasks.test]
category = "development"
command = "pytest"

[tasks.clean]
script = """
python setup.py clean
rm -rf .mypy_cache
rm -rf .pytest_cache
"""

[tasks.prebuild]
category = "deployment"
script = """
docker build -f Dockerfile.manylinux_x86_64 -t manylinux_x86_64:develop .
docker build -f Dockerfile.manylinux_i686 -t manylinux_i686:develop .
"""

[tasks.build]
category = "deployment"
script = """
rm -rf discord_ext_audiorec.egg-info
rm -rf dist/*
python setup.py sdist
docker run --rm -v `pwd`:/io manylinux_x86_64:develop /io/build-wheels.sh
docker run --rm -v `pwd`:/io manylinux_i686:develop /io/build-wheels.sh
"""

[tasks.test-deploy]
category = "deployment"
script = """
twine upload --repository testpypi dist/*-manylinux_2_24_x86_64.whl
"""
